### PR TITLE
[0.10.0] Elective Syllabus

### PR DESCRIPTION
**Pull request by SiravitPhokeed**
## Features
- More details in Elective Details Card
  Resolves FRO-96 [(link)](https://linear.app/skiso/issue/FRO-96/more-details-in-elective-details-card)
  - New description design allows for longer text
    Resolves FRO-91
  - PDF Preview Dialog for Elective syllabus
    Resolves FRO-92
- Unselected state for Learn Electives page
  Resolves FRO-101

## Fixes
- Choose Button in Elective Details Card erroneously hidden if the Student has not enrolled in any Elective yet
  Note: Choose Button in Elective Details Card remains hidden on desktop, which is the correct behavior
- Added bottom padding to bottom of Chip Sets in Elective Details Card so each inset Card is concentric
- Electives with multiple rooms used to show as one Room Chip, now separated
- Elective Details Card expands (instead of scroll) when content exceeds original height
- Dialogs nested in Lookup Details Dialog does not work
- White box behind Google One Tap UI on mobile dark mode

## Preview
This is the current main feature PR. Preview available at https://pr.mysk.school/.

### CODE REVIEW

**Review by smartwhatt — APPROVED** [review]
LGTM!!

**Comment by SiravitPhokeed** [comment]
> @Nubboyy
> This is probably because my account isn't in any classroom.

DM me your student ID and preferred Classroom, I’ll put you in a that Classroom for you.

**Comment by SiravitPhokeed** [comment]
> @Sun-52
> I selected the elective subject, but in the printout it says that I didn't select any elective yet.

This looks like a MySK API issue. @smartwhatt will investigate when he gets home.

**Review by Sun-52 — APPROVED** [review]
The printout says that the student didn't choose an elective yet, but the student had already chosen an elective.

There is no card to navigate from the learn page to the elective page. (I am not sure if it is because of the date.)

**Comment by SiravitPhokeed** [comment]
> @Sun-52
> The printout says that the student didn't choose an elective yet

@smartwhatt has confirmed that this is a MySK issue and the fix is pending deployment.

**Comment by smartwhatt** [comment]
> > @Sun-52
> > The printout says that the student didn't choose an elective yet
> 
> @smartwhatt has confirmed that this is a MySK issue and the fix is pending deployment.

The fix have been deployed

**Pull request merged**
