### PR TITLE
Form Creator

### LINKED ISSUE #58: Middleware could be utilized in protecting pages
**Is your feature request related to a problem? Please describe.**
When users visit a page they are not supposed to visit, a statically generated page shows for a few seconds before the user is redirected away from the page. This exposes private information of the school to the public.

**Describe the solution you’d like**
A middleware will redirect the user immediately even before showing the page.

**Additional context**
Read the documentation on middleware [here](https://nextjs.org/docs/advanced-features/middleware).

### PR DESCRIPTION
**Pull request by SiravitPhokeed**
image

**Features**
- Authentication middleware
  Resolves #58
- Form Creator

### CODE REVIEW

**Review by Jimmy-Tempest — APPROVED** [review]
LGTM however I want to make sure of a few things
1. most of the file changes are just refactoring to middleware right?
2. there's no backend interaction for admin side of form right?

**Comment by SiravitPhokeed** [comment]
1. Yes.
2. Admins can create, edit, and view forms but cannot submit data for that form.
  Class advisors will be able to view form responses for their classes.

**Comment by Jimmy-Tempest** [comment]
> 1. Yes.
> 2. Admins can create, edit, and view forms but cannot submit data for that form.
>    Class advisors will be able to view form responses for their classes.

For number 2 I mean is the interaction implemented in the code or not?

**Comment by SiravitPhokeed** [comment]
No.

**Comment by Jimmy-Tempest** [comment]
When would that be due? Is it required for this release (tomorrow)?

**Comment by SiravitPhokeed** [comment]
This is not a priority right now. We still don’t have a way for class advisors to view student responses which should come first (ideally this release but I think we’ll have it be the first thing we do after the release). We’ll think about the Form Creator’s due date after that’s done.

**Pull request merged**
