### PR TITLE
Better Teacher Setup Flow

### LINKED ISSUE #86: Pressing `Enter ⏎` in Login triggers Forgot Password
**Describe the bug**
After filling the email and password, pressing <kbd>Enter ⏎</kbd> in Login triggers both the Forgot Password dialog and the Log in process.

**To Reproduce**

1. Go to `/account/login`
2. Enter valid email and password
3. Press <kbd>Enter ⏎</kbd>
4. See Forgot Password dialog, and the Learn/Teach page in a few seconds.

**Expected behavior**
It should just log in.

**Additional context**
This is probably caused by the Buttons being in a `form` element.

### LINKED ISSUE #95: Teacher can not view other room data
**Is your feature request related to a problem? Please describe.**
Teachers have no way of accessing the data from other classrooms (e.g. students, contacts, schedule, etc) using exclusively the UI

**Describe the solution you’d like**
A page to show list of classes teachers can access

### LINKED ISSUE #99: More prominent and clearer guidance on setting up a teacher account
**Is your feature request related to a problem? Please describe.**
Through user testing, it has been found that the current solution (describing the process in a Section in Welcome) does not adequately explain the teacher setup process. The teacher would either skip the Section or forget the process once they're in the app, thus becoming lost.

**Describe the solution you’d like**
Instead of describing the process, we guide them once they’re in the app. After Welcome, the Schedule should be blocked out with the message “To create your schedule, refer to the ’Subjects you teach’ section below and follow the instructions there.” After subject-class connections have been made, we unblock the Schedule, providing clear visual indication of where to go next.
For adding details to subject-class connections, the Add Subject Dialog could say “To add more details about your subject that’s unique to each class, use the ’See details’ button on each subject once you’re done.” just before the Add Button.

**Additional context**
Courtesy of Supannee and Atipol.

### LINKED ISSUE #100: Add Subject Dialog in add mode has invalid internal defaults
**Describe the bug**
The Edit Schedule Dialog in add mode has mismatching internal and visual defaults, with the internal default being either 0 or empty strings (which are invalid). This means the user just looking at the visual would assume no changes but can’t 

**To Reproduce**

1. Log in as a teacher
2. Go to `/teach/schedule`
3. Click on “Add period”
4. Fill in the form until it appears valid
5. See the Save Button is still disabled

**Expected behavior**
The internal and visual defaults should match.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by SiravitPhokeed**
image

**Features**
- Removed text guidance on Teacher setup because nobody (except Supannee apparently) reads that anyway
- More relevant guidance in components involved in Teacher setup
  Resolves #99
  - Schedule blocks editing if the user hasn’t connected a subject to classes; reason also shown
  - Add Subject Dialog has info on the next steps after connecting subjects to classes
- Teachers can view other classes’ Manage pages
  Resolves #95
- Preferences Section in Account
  - Language switcher
- Welcome now scrolls to the next Section automatically
- Landing Feed is now scrollable
- News Article image overhaul—images are no longer confined to 16:9 ratio
- `prefers-reduced-motion` support for Framer Motion—transform animations are disabled if the user has requested reduced motion

**Fixes**
- Edit Schedule Period Dialog in add mode has conflicting internal and visual defaults
  Fixes #100
- Pressing <kbd>Enter ⏎</kbd> in Login triggers the Forgot Password Dialog
  Fixes #86
- Periods in Elective Periods Reveal gets the duration from the longest period, not itself
- @ImSadudee’s info in About is outdated
  - GitHub name change
  - Website now offline
- Teachers who are not class advisors see that they are the class advisor of M.0
- Many components lack RLS support
  - Delete Schedule Period
  - Add Teacher
  - Edit Person

### CODE REVIEW

**Review by Jimmy-Tempest — APPROVED** [review]
LGTM!!

**Comment by Jimmy-Tempest** [comment]
also good luck on those merge conflicts

**Comment by SiravitPhokeed** [comment]
> also good luck on those merge conflicts

There are merge conflicts??

**Comment by Jimmy-Tempest** [comment]
wait

**Comment by Jimmy-Tempest** [comment]
nvm it's just blocked

**Review by Temp9699 — APPROVED** [review]
LGTM

**Pull request merged**
