### PR TITLE
Welcome

### LINKED ISSUE #80: Welcome
**Figma design**
image

**Figma prototype**
[Link to prototype](https://www.figma.com/proto/NF91V1N9blvG6slT68Z5bx/Our-SK?page-id=3374%3A6442&node-id=3374%3A6443&viewport=443%2C340%2C0.4&scaling=scale-down)

### PR DESCRIPTION
**Pull request by SiravitPhokeed**
image

**Features**
- Welcome
  Resolves #80
- Prefix dropdowns are replaced by Thai prefix and English prefix text fields

**Fixes**
- Admin page protection is faulty

**Notes to QA**
Accounts usually reserved for testing have already been setup and therefore can’t be used to test Welcome. Use other accounts instead.

### CODE REVIEW

**Review by Jimmy-Tempest — APPROVED** [review]
LGTM!

**Review by Temp9699 — APPROVED** [review]
lgtm

**Review by Temp9699 — APPROVED** [review]
lgtm

**Comment by Temp9699** [comment]
> lgtm

Sorry I reviewed the wrong PR

**Pull request merged**
