### PR TITLE
Beta Release 0.11.0

### PR DESCRIPTION
**Pull request by SiravitPhokeed**
## Features
- Special logo for June — contributed by @pixelpxed
- Updated all instances of the MySK logo to use the original SVG and current Material colors
  - Including app icons and favicons
  - The SVG we’ve been using was traced from a blurry screenshot because we couldn’t find the original SVG at the time
- OpenGraph support in the landing
- Report Issue Dialog in Navigation Drawer

## Code Changes
- Migrated `account.json` to `next-translate`
- Migrated to Serwist (replaces `next-pwa`)
- Redid `.gitignore`, `postcss.config.mjs`, and `next.config.mjs` to match modern standards
- `useBreakpoint` hook
  - `Breakpoint` enum
- `useListDetail` hook
  - Classes
  - Learn/Teach/Manage Electives
  - Search Students/Teachers/Documents

## Fixes
- Electives Bulk Print throws when a Student without a Classroom in enrolled in an Elective
- News Articles were erroneously made private, which disabled OpenGraph
  - Sharing a News Article link should show OpenGraph now
- The header part Document Details Card has the wrong color

## Preview
Preview available at https://preview.mysk.school/.

### CODE REVIEW

**Review by pixelpxed — DISMISSED** [review]
I love how we're doing a PR in the middle of a meeting, legitimate though!

**Review by CursorWind — DISMISSED** [review]
Yippie

**Review by Sun-52 — APPROVED** [review]
LGTM

**Review by pixelpxed — APPROVED** [review]
ถูกทำนองคลองธรรม

**Review by CursorWind — APPROVED** [review]
LGTM!!!

**Review by Sun-52 — APPROVED** [review]
LGTM

**Pull request merged**
