### PR TITLE
[0.4.0] Lookup Landing/Orders/School Documents

### PR DESCRIPTION
**Pull request by SiravitPhokeed**
image
image

**Features**
- Migration to SKCom v3.0.3
- New pages
  - School Lookup (landing for Lookup)
  - Lookup Orders
  - Lookup Documents

**Fixes**
- Back Button in error handling pages scrolls with the page
- Language toggle in Navigation Drawer has no ripple effect

### CODE REVIEW

**Review by Jimmy-Tempest — CHANGES_REQUESTED** [review]
LGTM in terms of code but lookup seems to doesn't check the user permission
I used my student account to access lookup and can browse all of the orders which only have `include_teacher` as true

**Review by Temp9699 — APPROVED** [review]
LGTM other than the problem Jimmy mentioned

**Review by Jimmy-Tempest — APPROVED** [review]
All good but does it make sense to allow student to see the order at all? There are no case where the order to be seen by student anyways

**Review by Temp9699 — APPROVED** [review]
lgtm

**Pull request merged**
